import type { AnalysisOutcome } from '../claude/analysis.ts';

export type CommentaryMode = 'standard' | 'loading' | 'ai';
export type CommentaryTone = 'standard' | 'loading' | 'ai' | 'caution';

export interface CommentaryState {
  readonly mode: CommentaryMode;
  readonly label: string;
  readonly tone: CommentaryTone;
  readonly icon: string;
}

export interface CommentaryStateInput {
  readonly outcome: AnalysisOutcome | null;
  readonly isLoading: boolean;
  readonly apiKeyConfigured: boolean;
}

const STANDARD: CommentaryState = {
  mode: 'standard',
  label: 'Standard explanation · generated locally, no AI',
  tone: 'standard',
  icon: '◇',
};

export function commentaryStateFor({
  outcome,
  isLoading,
  apiKeyConfigured,
}: CommentaryStateInput): CommentaryState {
  if (!apiKeyConfigured) return STANDARD;
  if (isLoading) {
    return {
      mode: 'loading',
      label: 'Asking Claude…',
      tone: 'loading',
      icon: '↻',
    };
  }
  if (outcome === null || outcome.kind === 'failed' || outcome.fromRecording) return STANDARD;

  const model = outcome.model === null ? '' : ` · ${outcome.model}`;
  return {
    mode: 'ai',
    label: `${outcome.checked.trustworthy ? 'AI-generated by Claude' : 'AI-generated by Claude · discrepancies flagged'}${model}`,
    tone: outcome.checked.trustworthy ? 'ai' : 'caution',
    icon: outcome.checked.trustworthy ? '✦' : '!',
  };
}
