// @vitest-environment node

import { describe, expect, it } from 'vitest';
import type { AnalysisOutcome } from '../claude/analysis.ts';
import type { CheckedAnalysis } from '../claude/crosscheck.ts';
import { commentaryStateFor } from './commentaryState.ts';

function checked(trustworthy: boolean): CheckedAnalysis {
  return {
    analysis: {
      summary: 'Pay the expensive debt first.',
      debtNotes: [],
      tradeoffs: [],
      watchOuts: [],
    },
    discrepancies: trustworthy
      ? []
      : [{
          accountId: 'card' as never,
          accountName: 'Credit card',
          claimed: '$10.00',
          actual: '$12.00',
          difference: '+$2.00',
        }],
    trustworthy,
    notesInPlanOrder: [],
    caveat: trustworthy ? null : 'The written commentary quoted a figure that does not match.',
  };
}

function ok(fromRecording: boolean, trustworthy = true): AnalysisOutcome {
  return {
    kind: 'ok',
    checked: checked(trustworthy),
    unexplained: [],
    latencyMs: 250,
    fromRecording,
    model: 'claude-test',
  };
}

describe('commentaryStateFor', () => {
  it('uses a standard local state when there is no API key', () => {
    expect(commentaryStateFor({ outcome: null, isLoading: false, apiKeyConfigured: false })).toMatchObject({
      mode: 'standard',
      label: 'Standard explanation · generated locally, no AI',
      icon: '◇',
    });
  });

  it('treats recorded replies as standard local commentary', () => {
    expect(commentaryStateFor({ outcome: ok(true), isLoading: false, apiKeyConfigured: true }).mode).toBe('standard');
  });

  it('keeps failed calls in the standard local state', () => {
    const outcome: AnalysisOutcome = { kind: 'failed', reason: 'No key', remedy: 'Add a key.' };
    expect(commentaryStateFor({ outcome, isLoading: false, apiKeyConfigured: true }).mode).toBe('standard');
  });

  it('shows a loading state while a live call is in flight', () => {
    expect(commentaryStateFor({ outcome: null, isLoading: true, apiKeyConfigured: true })).toMatchObject({
      mode: 'loading',
      label: 'Asking Claude…',
      icon: '↻',
    });
  });

  it('labels a live reply as AI-generated', () => {
    expect(commentaryStateFor({ outcome: ok(false), isLoading: false, apiKeyConfigured: true })).toMatchObject({
      mode: 'ai',
      tone: 'ai',
      label: 'AI-generated by Claude · claude-test',
      icon: '✦',
    });
  });

  it('keeps live replies with discrepancies in the AI state with a caution tone', () => {
    expect(commentaryStateFor({ outcome: ok(false, false), isLoading: false, apiKeyConfigured: true })).toMatchObject({
      mode: 'ai',
      tone: 'caution',
      icon: '!',
    });
  });
});
